site_name: Masha's Notes
site_description: Short bytes of information, code snippets or articles that I want to keep handy.
copyright: Made by Francis Masha.
repo_name: mashafrancis/notes
repo_url: https://github.com/mashafrancis/notes
edit_uri: edit/main/docs/
docs_dir: ./docs
site_dir: ./site

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    logo: material/xml
  favicon: img/favicon.png
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - navigation.instant
    - search.share
    - search.highlight
    - search.suggest
  font:
    text: Noto Sans
    code: IMB Plex Mono

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true
  - roamlinks

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mashafrancis

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css